[global]
disable = ["MD013"]
exclude = [
  "third_party/**",
  "build/**",
  "assets/.local/**",
  "assets/build/**",
  ".local/**",
  ".wip/**",
  ".benchgen*/**",
]
respect-gitignore = true

[per-file-ignores]
"README.md" = ["MD033"]

[MD024]
siblings-only = true
